import reflex as rx

def navigation():
    """Navigation component providing links to all application pages."""
    return rx.hstack(
        rx.link(
            "Home",
            href="/",
            is_active=rx.state.router.page.path == "/",
            padding="2",
            border_radius="md",
            color=rx.cond(rx.state.router.page.path == "/", "blue.700", "gray.700"),
            bg=rx.cond(rx.state.router.page.path == "/", "blue.50", "transparent"),
            text_decoration="none",
            _hover={"bg": "gray.100"},
        ),
        rx.link(
            "Data Selection",
            href="/data",
            is_active=rx.state.router.page.path == "/data",
            padding="2",
            border_radius="md",
            color=rx.cond(rx.state.router.page.path == "/data", "blue.700", "gray.700"),
            bg=rx.cond(rx.state.router.page.path == "/data", "blue.50", "transparent"),
            text_decoration="none",
            _hover={"bg": "gray.100"},
        ),
        rx.link(
            "Feature Engineering",
            href="/features",
            is_active=rx.state.router.page.path == "/features",
            padding="2",
            border_radius="md",
            color=rx.cond(rx.state.router.page.path == "/features", "blue.700", "gray.700"),
            bg=rx.cond(rx.state.router.page.path == "/features", "blue.50", "transparent"),
            text_decoration="none",
            _hover={"bg": "gray.100"},
        ),
        rx.link(
            "Model Training",
            href="/training",
            is_active=rx.state.router.page.path == "/training",
            padding="2",
            border_radius="md",
            color=rx.cond(rx.state.router.page.path == "/training", "blue.700", "gray.700"),
            bg=rx.cond(rx.state.router.page.path == "/training", "blue.50", "transparent"),
            text_decoration="none",
            _hover={"bg": "gray.100"},
        ),
        rx.link(
            "RL Training",
            href="/reinforcement",
            is_active=rx.state.router.page.path == "/reinforcement",
            padding="2",
            border_radius="md",
            color=rx.cond(rx.state.router.page.path == "/reinforcement", "blue.700", "gray.700"),
            bg=rx.cond(rx.state.router.page.path == "/reinforcement", "blue.50", "transparent"),
            text_decoration="none",
            _hover={"bg": "gray.100"},
        ),
        rx.link(
            "Evaluation",
            href="/evaluation",
            is_active=rx.state.router.page.path == "/evaluation",
            padding="2",
            border_radius="md",
            color=rx.cond(rx.state.router.page.path == "/evaluation", "blue.700", "gray.700"),
            bg=rx.cond(rx.state.router.page.path == "/evaluation", "blue.50", "transparent"),
            text_decoration="none",
            _hover={"bg": "gray.100"},
        ),
        spacing="4",
        padding="4",
        overflow_x="auto",
        width="100%",
        justify="center",
        align_items="center",
        bg="white",
        border_bottom="1px solid",
        border_color="gray.200",
    )